function SaveDataSet(ComplexProteinLabel,NumberOfProteinsInComplexes,NumberOfKnownProteinsInComplexes,...
    OverlapComplexesFlag,ProteinLabel,ProteinLabelPairs,A,N,NumInteractionProtein,MaxNumInteractionProtein,...
    IndicesInteractionProtein,ComplexName,ProteinName)

ComplexPath = append('DataSets/Complex/',ComplexName)
ProteinPath = append('DataSets/Protein/',ProteinName)
save(ComplexPath,'ComplexProteinLabel', ...
                                             'NumberOfProteinsInComplexes', 'NumberOfKnownProteinsInComplexes', ...
                                             'OverlapComplexesFlag');

save(ProteinPath,'ProteinLabel','ProteinLabelPairs','A','N','NumInteractionProtein','MaxNumInteractionProtein','IndicesInteractionProtein');
